### ISSUE TITLE
ISS3 Modificar footer.

### ISSUE THREAD

**Issue by OmarGReyes** [Equipo-111/semana-1-111#3]
La sección footer **DEBE** cumplir con los siguientes requerimientos:

 Se deberá crear el pie del sitio web en donde se incluye información de contacto, **deberá** estar dividido en **dos partes**: 
1) una se tendrá la información del sitio web como el motivante del desarrollo y **el enlace al repositorio de Github**. 
2) La otra los **contacto de los miembros** del equipo con **sus nombres y roles.** 
3) La sección debe de estar en un **tag <footer></footer>**.

**Comment by egfarfan** [comment]
texto incluido
